# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tubetiquette
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Sustainable clothing brand with t-shirt designs illustrating the etiquette around tubs and tubes, featuring cats.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tubetiquette
twitter_url: https://twitter.com/tubetiquette
instagram_url: https://instagram.com/tubetiquette
# github_username:  tubetiquette
store_url: https://tubetiquette.teemill.com/collection/designs/

# Build settings
markdown: kramdown
# theme: jekyll-theme-slat #e
# remote-theme: benbalter/retlab #andrewbanchich/forty-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

## homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

## https://jekyllrb.com/docs/collections/
collections: 
    posts_parallel: 
        output: true

permalink: pretty

# bundle exec jekyll serve
# [jekyllrb.com](https://jekyllrb.com/)
# https://jekyllrb.com/docs/themes/#overriding-theme-default
# https://jekyllrb.com/docs/step-by-step/08-blogging/
# https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
